language: java
cache:
  directories:
  - $HOME/.m2/repository

sudo: required

jdk:
  - oraclejdk8

services:
  - docker

env:
  - SOURCE=debezium
  - SOURCE_DIR=${PWD}/integration_test/${SOURCE}
  - DOCKER_EXEC='docker exec -it'

before_install:
  - sudo service mysql-5.6 stop || sudo service mysql stop
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get install jsvc

install: true

script:
  - integration_test/test.sh

after_script:
  - mvn clean
